baseURL: "https://netanyawilliams.github.io" 
title: Netanya Williams
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: About Me
          url: books/
          weight: 1 
        - name: Research
          url: papers/
          weight: 2
        - name: Outreach
          url: data/
          weight: 3 

params:
    description: "I am a MS student in the UConn EEB department interested in parasite imaging and phylogenetics. Parasitic copepod taxonomy, systematics, and host association."
    author: Netanya Williams
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Netanya Williams
          subtitle: "I’m a Masters student in the Bernot Lab interested in parasitic copepod systematics. I study the taxonomy of Pseudotaeniacanthus, a group of parasitic copepods of marine eels. My current work focuses on new species descriptions and the phylogenetic relationships of the genus. Prior to joining the Bernot Lab, I earned my BA in Biological Sciences at the University of Connecticut in 2023 and worked for 2 years doing research on the taxonomy and host associations of tapeworms of carcharhinid sharks and rays with Janine Caira."
          imageUrl: "okpicture.jpeg"
          imageWidth: 185
          imageHeight: 185
          imageTitle: Netanya Williams
          buttons:
            - name: About Me
            #  url: books/
            - name: Research
            #  url: papers/
            - name: Outreach
            #  url: data/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:netanya.williams@uconn.edu
        - name: Location
          url: location/
        - name: GitHub
          url: https://github.com/netanyawilliams
        - name: Twitter
          url: https://twitter.com/NetanyaAW

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Netanya Williams"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
